### ISSUE TITLE
Support one-hot encoding

### ISSUE THREAD

**Issue by ChosunOne** [tensorflow/rust#189] opened 2019-02-14 20:45 UTC
One hot encoding is useful for reducing the boilerplate code needed when dealing with categorical data, and many of the other TensorFlow APIs support it ([C++ reference](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/one-hot.html)).

**Comment by adamcrume** [comment] 2019-02-18 20:44
`OneHot` is a standard operation, so it can be done today, just with a fair bit of boilerplate:

```rust
let mut g = Graph::new();
// These are the inputs and will be different depending on your use case.
let indices = {
    let mut nd = g.new_operation("Placeholder", "indices")?;
    nd.set_attr_type("dtype", DataType::Int32)?;
    nd.set_attr_shape("shape", &Shape(Some(vec![])))?;
    nd.finish()?
};
let depth = {
    let mut nd = g.new_operation("Const", "depth")?;
    nd.set_attr_type("dtype", DataType::Int32)?;
    nd.set_attr_tensor("value", Tensor::from(10))?;
    nd.finish()?
};
let off_value = {
    let mut nd = g.new_operation("Const", "off_value")?;
    nd.set_attr_type("dtype", DataType::Float)?;
    nd.set_attr_tensor("value", Tensor::from(0.0f32))?;
    nd.finish()?
};
let on_value = {
    let mut nd = g.new_operation("Const", "on_value")?;
    nd.set_attr_type("dtype", DataType::Float)?;
    nd.set_attr_tensor("value", Tensor::from(1.0f32))?;
    nd.finish()?
};
// This can be copied verbatim, except for the node name.
let one_hot = {
    let mut nd = g.new_operation("OneHot", "OneHot")?;
    nd.add_input(Output {
        operation: indices,
        index: 0,
    });
    nd.add_input(Output {
        operation: depth,
        index: 0,
    });
    nd.add_input(Output {
        operation: on_value,
        index: 0,
    });
    nd.add_input(Output {
        operation: off_value,
        index: 0,
    });
    nd.finish()?
};
```

I'm considering ways to reduce some of this boilerplate, but the problem is not specific to `OneHot`.

**Comment by ChosunOne** [comment] 2019-02-21 01:39
Thanks for the reply!  It seems the API relies a lot on "graph.new_operation".  Is there an open issue for making aliases for those function calls (for better IDE hint support)?

**Comment by adamcrume** [comment] 2020-04-01 19:28
We've recently added generated code for standard ops, so you can do this with a lot less boilerplate now.  It's currently experimental and requires the `experimental_training` feature, but you should be able to do:

```rust
let indices = ops::Placeholder::new()
    .dtype(DataType::Int32)
    .build(&mut scope.with_op_name("indices"))?;
let one_hot = ops::one_hot(
    indices,
    /* depth */ ops::constant(10i32, &mut scope)?,
    /* on_value */ ops::constant(1.0f32, &mut scope)?,
    /* off_value */ ops::constant(0.0f32, &mut scope)?,
    &mut scope)?;
```

Or you can use the `ops::OneHot` builder if you need more customization.

You can see more examples of using the generated ops in https://github.com/tensorflow/rust/blob/master/examples/xor.rs.

**Comment by adamcrume** [comment] 2020-10-17 05:07
I assume that the issue is addressed by the new builder code described in the previous comment (which no longer requires the `experimental_training` feature), so I'm closing this issue.  If this doesn't actually address your concern, feel free to re-open this issue.

**Closed by adamcrume** 2020-10-17 05:07 UTC
